### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by zdavatz** [tkipf/gcn#6]
Hi 

I just ran

`python /home/zeno/.software/gcn/gcn/train.py --dataset citeseer`

but this results in

`Traceback (most recent call last):
  File "/home/zeno/.software/gcn/gcn/train.py", line 29, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data(FLAGS.dataset)
  File "/usr/local/src/anaconda3/lib/python3.5/site-packages/gcn-1.0-py3.5.egg/gcn/utils.py", line 30, in load_data
    objects.append(pkl.load(open("data/ind.{}.{}".format(dataset_str, names[i])), encoding='latin1'))
  File "/usr/local/src/anaconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

Do I need to use a different Python version?

Thank you for your Feedback.

**Comment by tkipf** [comment]
Thanks for reporting. This should have been fixed with commit https://github.com/tkipf/gcn/commit/14e6bbacabed543548cf8114a672cf1a6de85f84 . Have you pulled the latest version?

**Comment by zdavatz** [comment]
My versions are: 
`Python 3.5.2 :: Anaconda 4.1.1 (64-bit)`

**Comment by tkipf** [comment]
Thanks - https://github.com/tkipf/gcn/commit/50de2c62978bd5d8ec4458fdcb7383ada69ac2d8 should fix this now. Can you pull and try again?

**Comment by zdavatz** [comment]
thank, I pulled, now I get:

`~/.software/gcn/gcn> python /home/zeno/.software/gcn/gcn/train.py --dataset citeseer
Traceback (most recent call last):
  File "/home/zeno/.software/gcn/gcn/train.py", line 29, in <module>
    adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data(FLAGS.dataset)
  File "/usr/local/src/anaconda3/lib/python3.5/site-packages/gcn-1.0-py3.5.egg/gcn/utils.py", line 30, in load_data
    if sys.version_info > (3, 0):
  File "/usr/local/src/anaconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
`

**Comment by tkipf** [comment]
Thanks, can you try re-running `python setup.py install` and - as a last resort - delete all associated `.pyc` files?

**Comment by zdavatz** [comment]
thanks, this worked now

python train.py --dataset citeseer

**Comment by saria85** [comment]
Hi 

I have the same issue, I did the instructions but it didnt fix,
I have ubuntu 16.10 , python 3.6  tensorflow 1.1
firstly I freez the graph then I wanna to optimize the freezed graph, when it wants to read the freezed data it raises error 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 364: invalid start byte

please hepl me soonnn, I get stuck in this bugg no fix for that

**Comment by tkipf** [comment]
Hi, thanks for reporting your issue. I'll have a look at this early next week, in the meantime you can try running the code with python 2.7 instead.

**Comment by saria85** [comment]
woow thank you really for your quick reply,
the problem is I want to use this optimized model in android studio , as I remember the version of python has to be +3.5,
so if I run that with 2.7 rest of my work wont be applied,

there isnt any wheel to fix this unicode problem?

**Comment by tkipf** [comment]
I assume by freezing the graph, you probably pickle it in some way or another and then reload it from disk. When loading the pickled file, you have to make sure to set the encoding to `latin1` (see https://github.com/tkipf/gcn/commit/50de2c62978bd5d8ec4458fdcb7383ada69ac2d8 for an example) in case you're using python3. Hope this helps.

**Comment by saria85** [comment]
thanks again, I have deadline, I hope this can be fixed ,

this is my code for freezing then optimizing,
may I ask you to have a quick glance on that,

def freeze_graph(model_folder):
    # We retrieve our checkpoint fullpath

    checkpoint = tf.train.get_checkpoint_state(model_dir)
    input_checkpoint = checkpoint.model_checkpoint_path

    # We precise the file fullname of our freezed graph
    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/frozen_model.pb"

    # Before exporting our graph, we need to precise what is our output node
    # This is how TF decides what part of the Graph he has to keep and what part it can dump
    # NOTE: this variable is plural, because you can have multiple output nodes
    output_node_names = [n.name for n in tf.get_default_graph().as_graph_def().node]


    # We clear devices to allow TensorFlow to control on which device it will load operations
    clear_devices = True

    # We import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)

    # We retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    print(input_graph_def)

    # We start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)
        print(input_checkpoint)
        # We use a built-in TF helper to export variables to constants
        output_graph_def = tf.graph_util.convert_variables_to_constants(
            sess,  # The session is used to retrieve the weights
            input_graph_def,  # The graph_def is used to retrieve the nodes
            output_node_names  # The output node names are used to select the usefull nodes
        )

        # Finally we serialize and dump the output graph to the filesystem
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_folder", type=str, help="Model folder to export")
    args = parser.parse_args()

    freeze_graph(args.model_folder)



    output_node_names = [n.name for n in tf.get_default_graph().as_graph_def().node]
    input_node_names = [n.name + '=>' +  n.op for n in tf.GraphDef().node if n.op in ( 'Softmax','Placeholder')]
    input_graph_def = tf.GraphDef()
    checkpoint = tf.train.get_checkpoint_state(model_dir)
    input_checkpoint = checkpoint.model_checkpoint_path

    # We precise the file fullname of our freezed graph
    absolute_model_folder = "/".join(input_checkpoint.split('/')[:-1])
    output_graph = absolute_model_folder + "/frozen_model.pb"

    with tf.gfile.Open(output_graph, "r") as f:
        
        data = f.read()
        input_graph_def.ParseFromString(data)

    output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        input_graph_def,
        input_node_names,  # an array of the input node(s)
        output_node_names,  # an array of output nodes
        tf.float32.as_datatype_enum)

    # Save the optimized graph
    output_optimized_graph_name = 'optimized_' + model_name + '.pb'
    f = tf.gfile.FastGFile(output_optimized_graph_name, "w")
    f.write(output_graph_def.SerializeToString())

**Comment by tkipf** [comment]
Can you try replacing `with tf.gfile.Open(output_graph, "r") as f:` with `with tf.gfile.Open(output_graph, "rb") as f:`?

**Comment by saria85** [comment]
I had already tried that but didnt work, but now is working, 
Dont know how to thank you,

Now it says 
assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: input_1 is not in graph

I just elicit the input names by code , so whats the problem!!
sorry I know its not related, but if you have some ideas I appreciate it

**Comment by tkipf** [comment]
Glad it worked. I think the other issue is unrelated to this one and you might be better off just going through your code with a line-by-line debugger.

**Comment by saria85** [comment]
yea its not related , thanks a lot for your help, :)

**Comment by MrNakum** [comment]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-27-0da2181ac8b3> in <module>()
----> 1 train_top_model()

<ipython-input-26-d9498d5b21eb> in train_top_model()
      1 def train_top_model():
----> 2     train_data = np.load(open('bottleneck_features_train.npy'))
      3     train_labels = np.array(
      4         [0] * (nb_train_samples / 2) + [1] * (nb_train_samples / 2))
      5 

/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    400         _ZIP_PREFIX = b'PK\x03\x04'
    401         N = len(format.MAGIC_PREFIX)
--> 402         magic = fid.read(N)
    403         # If the file size is less than N, we need to make sure not
    404         # to seek past the beginning of the file

/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte



any have idea what is the solution of it ?

**Comment by tkipf** [comment]
Doesn't look like the issue you get has something to do with our code base. 

You can try replacing `open('bottleneck_features_train.npy')` with `open('bottleneck_features_train.npy', 'rb')` or trying a different python version.

**Comment by ptpankajtiwari5** [comment]
Hi,
I am also facing this issue with 'utf-8' codec can't decode byte 0x93 in position 10: invalid start byte.
and I am unable to run my program..

bellow is the issue

POST
--
http://127.0.0.1:8000/inbound/batch-selection/
1.11.9
UnicodeDecodeError
'utf-8' codec can't decode byte 0x93 in position 10: invalid start byte
/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/codecs.py in decode, line 321
/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/bin/python
3.5.2
['/home/pankaj/NewDjangoProject/27feb2018/28feb18/InProcessing/Incoming',  '/home/pankaj/pycharm-community-2017.3.1/helpers/pydev',  '/home/pankaj/NewDjangoProject/27feb2018/28feb18/InProcessing/Incoming',  '/home/pankaj/pycharm-community-2017.3.1/helpers/pydev',  '/home/pankaj/.PyCharmCE2017.3/system/cythonExtensions',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python35.zip',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf',  '/home/pankaj/NewDjangoProject/27feb2018/latest/InProcessing/Incoming/venv/lib/python3.5/site-packages/odf']

**Comment by tkipf** [comment]
@ptpankajtiwari5: Does this have to do anything with the repository here or is this completely unrelated and you came here via Google search? In the latter case, I'm afraid you're in the wrong place ;)

**Comment by Jahnavi34** [comment]
I have this server code with me where i am trying to send the encrypted data to the client and at the client side the encrypted data must be decrypted.But I am getting this error at the client side .Please help me

**** 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte**** 
The below one is my sever code

`import socket 
import threading
import pyaes
HEADER = 64
PORT = 5050
SERVER = socket.gethostbyname(socket.gethostname())
ADDR = (SERVER, PORT)
FORMAT = 'utf-8'
DISCONNECT_MESSAGE = "DISCONNECT!!!"

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind(ADDR)

def handle_client(conn, addr):
    print(f"[NEW CONNECTION] {addr} connected.")

    connected = True
    while connected:
        msg_length = conn.recv(HEADER).decode(FORMAT)
        if msg_length:
            msg_length = int(msg_length)
            msg = conn.recv(msg_length).decode(FORMAT)
            if msg == DISCONNECT_MESSAGE:
                connected = False
            

            # A 256 bit (32 byte) key
            key = "This_key_for_demo_purposes_only!"
            plaintext = "Text may be any length you wish, no padding is required"

            # key must be bytes, so we convert it
            key = key.encode('utf-8')

            aes = pyaes.AESModeOfOperationCTR(key)    
            ciphertext = aes.encrypt(plaintext)

            # show the encrypted data

            print(f"[{addr}] {msg}")
            conn.send(str(ciphertext).encode(FORMAT))

    conn.close()
        
def start():
    server.listen()
    print(f"[LISTENING] Server is listening on {SERVER}")
    while True:
        conn, addr = server.accept()
        thread = threading.Thread(target=handle_client, args=(conn, addr))
        thread.start()
        print(f"[ACTIVE CONNECTIONS] {threading.activeCount() - 1}")
print("[STARTING] server is starting...")
start()
`
This is my client code where I am getting the error
`import socket
import pyaes

HEADER = 64
PORT = 5050
FORMAT = 'utf-8'
DISCONNECT_MESSAGE = "DISCONNECT!!!"
SERVER = socket.gethostbyname(socket.gethostname())
ADDR = (SERVER, PORT)
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(ADDR)

def send(msg):
    message = msg.encode(FORMAT)
    msg_length = len(message)
    send_length = str(msg_length).encode(FORMAT)
    send_length += b' ' * (HEADER - len(send_length))
    client.send(send_length)
    client.send(message)
    # decrypted data is always binary, need to decode to plaintext
    key=input("enter key to decrypt")
    key = key.encode('utf-8')
    aes = pyaes.AESModeOfOperationCTR(key) 
    f=client.recv(2048).decode(FORMAT)
    decrypted = aes.decrypt(f).decode('utf-8')
    print(decrypted)




a=input("enter any message to send to server:")
send(a)
b=input("enter any message to send to server")
send(b)
#input("enter any message to send to server:")


send(DISCONNECT_MESSAGE)
`
